# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15GgTSVLJEpL1jSATcsIz7vmhg-KOhF2b

# Face Recognition Model
"""

!pip install face_recognition

import face_recognition

class Person:
    def __init__(self, name, roll_no, image_path):
        self.name = name
        self.roll_no = roll_no
        self.image_path = image_path

subh = Person("Abdul Subhan", "2206270", "subh.jpg")
anu = Person("Anushka Verma", "2202004", "anu.jpg")
utk = Person("Utkarsh Ranjan", "2206177", "utk.jpg")
mat = Person("Maithilee Pardhi", "2204189", "mat.jpg")
div = Person("Divyansh", "2206015", "div1.jpg")
students = {
    subh.roll_no : subh,
    anu.roll_no : anu,
    utk.roll_no : utk,
    mat.roll_no : mat,
    div.roll_no : div,
}

s = students["2206015"]
known_image = face_recognition.load_image_file(s.image_path)
unknown_image = face_recognition.load_image_file("div2.jpg")

known_encoding = face_recognition.face_encodings(known_image)[0]
unknown_encoding = face_recognition.face_encodings(unknown_image)[0]

results = face_recognition.compare_faces([known_encoding], unknown_encoding)

if results[0]:
  export = s
else:
  print("Face is not matched")

